# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.0
_src_path: gh:martgra/typescript_template
author_email: martgra@gmail.com
author_name: Martin Gran
project_description: Landing page for Martin Gran
project_name: martgra-landing-page
typescript_strict: true
use_devcontainer: true
use_github_actions: true
use_vscode: true
