services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace

    volumes:
      - ..:/workspace
      - martgra_landing_page_extensions:/home/vscode/.vscode-server/extensions
      - martgra_landing_page_commandhistory:/home/vscode/commandhistory
      - martgra_landing_page_cache:/home/vscode/.cache
      - martgra_landing_page_bun:/home/vscode/.bun
      - /workspace/node_modules

    # Keep container running
    command: sleep infinity

volumes:
  martgra_landing_page_extensions:
  martgra_landing_page_commandhistory:
  martgra_landing_page_cache:
  martgra_landing_page_bun:
